# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-09 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import flights.validators
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Авиакомпания')),
                ('code', models.CharField(max_length=2, validators=[flights.validators.airline_code_validate], verbose_name='Код авиакомпании')),
            ],
            options={
                'verbose_name_plural': 'Авиалинии',
                'verbose_name': 'Авиалиния',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название аэропорта')),
                ('code', models.CharField(max_length=3, validators=[flights.validators.airport_code_validate], verbose_name='Код аэропорта')),
            ],
            options={
                'verbose_name_plural': 'Aэропорты',
                'verbose_name': 'Aэропорт',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название города')),
                ('code', models.CharField(max_length=3, validators=[flights.validators.city_code_validate], verbose_name='Код города')),
                ('timezone', timezone_field.fields.TimeZoneField(verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name_plural': 'Города',
                'verbose_name': 'Город',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[flights.validators.flight_number_validate], verbose_name='Номер рейса')),
                ('duration', models.DurationField(verbose_name='Продолжительность полета')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Airline', verbose_name='Авиалиния')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='flights.Airport', verbose_name='Город прибытия')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='flights.Airport', verbose_name='Город вылета')),
            ],
            options={
                'verbose_name_plural': 'Рейсы',
                'verbose_name': 'Рейс',
            },
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.City', verbose_name='Город'),
        ),
    ]
