# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-08 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import flights.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Авиакомпания')),
                ('code', models.CharField(max_length=2, validators=[flights.validators.airline_code_validate], verbose_name='Код авиакомпании')),
            ],
            options={
                'verbose_name': 'Авиалиния',
                'verbose_name_plural': 'Авиалинии',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название аэропорта')),
                ('code', models.CharField(max_length=3, validators=[flights.validators.airport_code_validate], verbose_name='Код аэропорта')),
            ],
            options={
                'verbose_name': 'Aэропорт',
                'verbose_name_plural': 'Aэропорты',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название города')),
                ('code', models.CharField(max_length=3, validators=[flights.validators.city_code_validate], verbose_name='Код города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[flights.validators.flight_number_validate], verbose_name='Номер рейса')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Airline', verbose_name='Авиалиния')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.City', verbose_name='Город'),
        ),
    ]
