# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-15 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleflight',
            name='time_of_departure',
            field=models.DateTimeField(verbose_name='Фактическое местное время вылета.'),
        ),
    ]
