# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-09 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_arr', to='flights.Airport', verbose_name='Город прибытия'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_dep', to='flights.Airport', verbose_name='Город вылета'),
        ),
    ]
